home/urls.py
from django.contrib import admin
from django.urls import path, include

from home import views as home
from home.views.agents_view import AgentListView
from home.views.agents_view import AgentDetailView
from home.views.map_view import MapListView
from home.views.map_view import MapDetailView
from home.views.weapons_view import WeaponListView
from home.views.weapons_view import WeaponDetailView
from home.views.home_view import HomeListView
from home.views.specs_view import SpecsListView
from home.views.news_view import NewsListView
from home.views.tutorials_view import TutorialListView
from home.views.premiers_view import PremierListView
from home.views.battlepass_view import BattlepassListView
from home.views.gameupdate_view import GameupdateListView


app_name = "home"

urlpatterns = [
    path('admin/', admin.site.urls),


    path(
        route='',
        view=HomeListView.as_view(),
        name='home',
    ),
    path(
        route='agents/',
        view=AgentListView.as_view(),
        name='agents',
    ),
    path(
        route='agents/<str:slug>/',
        view=AgentDetailView.as_view(),
        name='agent_detail',
    ),
    path(
        route='maps/',
        view=MapListView.as_view(),
        name='maps',
    ),
    path(
        route='maps/<str:slug>/',
        view=MapDetailView.as_view(),
        name='map_detail',
    ),
    path(
        route='weapons/',
        view=WeaponListView.as_view(),
        name='weapons',
    ),
    path(
        route='weapons/<str:slug>/',
        view=WeaponDetailView.as_view(),
        name='weapon_detail',
    ),
    path(
        route='specs/',
        view=SpecsListView.as_view(),
        name='specs',
    ),

    path(
        route='news/',
        view=NewsListView.as_view(),
        name='news',
    ),
    path(
        route='tutorials/',
        view=TutorialListView.as_view(),
        name='tutorials',
    ),
    path(
        route='premiers/',
        view=PremierListView.as_view(),
        name='premiers',
    ),
    path(
        route='battlepass/',
        view=BattlepassListView.as_view(),
        name='battlepass',
    ),
    path(
        route='gameupdates/',
        view=GameupdateListView.as_view(),
        name='gameupdates',
    ),


]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views as home
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
]

home/models/agents_model.py
from django.db import models
from cloudinary.models import CloudinaryField
from django.urls import reverse
from django.utils.text import slugify
# Create your models here.


class Agent(models.Model):

    # Agent
    name = models.CharField(max_length=100)
    bio = models.CharField(max_length=600)
    country = models.CharField(max_length=100)
    role = models.CharField(max_length=100)
    role_icon = CloudinaryField('img')
    number = models.CharField(max_length=50)

    img = CloudinaryField('img')
    avatar_icon = CloudinaryField('img')
    slug = models.SlugField()
    #
    # skill q
    skill_q_name = models.CharField(max_length=100)
    skill_q_icon = CloudinaryField('icon', transformation=[
                                   {'width': 180, 'height': 180, 'crop': 'fill'}])
    skill_q_video = CloudinaryField(resource_type='video')
    skill_q_description = models.CharField(max_length=700)

    # skill e
    skill_e_name = models.CharField(max_length=100)
    skill_e_icon = CloudinaryField('icon', transformation=[
                                   {'width': 180, 'height': 180, 'crop': 'fill'}])
    skill_e_video = CloudinaryField(resource_type='video')
    skill_e_description = models.CharField(max_length=700)

    # skill c
    skill_c_name = models.CharField(max_length=100)
    skill_c_icon = CloudinaryField('icon', transformation=[
                                   {'width': 180, 'height': 180, 'crop': 'fill'}])
    skill_c_video = CloudinaryField(resource_type='video')
    skill_c_description = models.CharField(max_length=700)

    # skill x
    skill_x_name = models.CharField(max_length=100)
    skill_x_icon = CloudinaryField('icon', transformation=[
                                   {'width': 180, 'height': 180, 'crop': 'fill'}])
    skill_x_video = CloudinaryField(resource_type='video')
    skill_x_description = models.CharField(max_length=700)

    class Meta:
        verbose_name = ("agent")
        verbose_name_plural = ("agents")

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name, allow_unicode=True)
        super(Agent, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('home:agent_detail', kwargs={'slug': self.slug})

home/models/battlepass_model.py
from django.db import models
from cloudinary.models import CloudinaryField
from django.urls import reverse
# Create your models here.

class Battlepass(models.Model):
    name = models.CharField(max_length=200)
    description =  models.CharField( max_length=1000)
    img = CloudinaryField('img')
    
    
    class Meta: 
        verbose_name = ("battlepass")
        verbose_name_plural = ("battlepasss")
        
    def __str__(self):
        return self.name
    

    

home/models/gameupdates_model.py
from django.db import models
from cloudinary.models import CloudinaryField
from django.urls import reverse

class Gameupdate(models.Model):
    
    #title
    title = models.CharField(max_length=1000)
    big_title = models.CharField(max_length=500)
    field2 = models.TextField(default=''' ''')  # Thay đổi từ CharField sang TextField

    
    class Meta:
        verbose_name = "gameupdate"
        verbose_name_plural = "gameupdates"
        
    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

home/models/home_model.py
from django.db import models
from cloudinary.models import CloudinaryField
from django.urls import reverse
from django.utils.text import slugify
from django.contrib.auth.models import User

# Create your models here.

class Home(models.Model):
    
    name = models.CharField(max_length=100)
    link = models.CharField(max_length=200)
    episode =  models.CharField(max_length=10)
    act = models.CharField(max_length=10)
    year = models.CharField(max_length=10)
    img = CloudinaryField('img')
    #data
    
    agent = models.CharField(max_length=50)
    maps = models.CharField(max_length=50)
    arresnals = models.CharField(max_length=50)
    specs = models.CharField(max_length=50)
    news = models.CharField(max_length=50)
    battlepass = models.CharField(max_length=50)
    premieres = models.CharField(max_length=50)
    tutorials = models.CharField(max_length=50)

    class Meta:
        verbose_name = ("home")
        verbose_name_plural = ("homes")
        
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('homes', kwargs={'slug': self.slug})

home/models/maps_model.py
from django.db import models
from cloudinary.models import CloudinaryField
from django.urls import reverse
from django.utils.text import slugify
# Create your models here.

class Map(models.Model):
    
    #Maps
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=500)
    img = CloudinaryField('img')
    slug = models.SlugField()
    status = models.CharField(max_length=400)
    
    #map detail
    
    map_location = models.CharField(max_length=250)
    
    img1 = CloudinaryField('img')
    img2 = CloudinaryField('img')
    img3 = CloudinaryField('img')
    img4 = CloudinaryField('img')
    img5 = CloudinaryField('img')
    img6 = CloudinaryField('img')
    img7 = CloudinaryField('img')
    img8 = CloudinaryField('img')
    
    

    class Meta:
        verbose_name = ("map")
        verbose_name_plural = ("maps")
    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name, allow_unicode=True)
        super(Map, self).save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse('home:map_detail', kwargs={'slug': self.slug})

home/models/newss_model.py
from django.db import models
from cloudinary.models import CloudinaryField
from django.urls import reverse
# Create your models here.

class News(models.Model):
    
    #News
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=500)
    img = CloudinaryField('img')
    datetime = models.DateTimeField(auto_now=False)  
    link = models.URLField(max_length=200)
    
    class Meta:
        verbose_name = ("news")
        verbose_name_plural = ("newss")

    def __str__(self):
        return self.name

home/models/premiers_model.py
from django.db import models
from cloudinary.models import CloudinaryField
from django.urls import reverse
# Create your models here.

class Premier(models.Model):
    
    #FAQ
    question = models.CharField(max_length=500)
    answer = models.CharField(max_length=1000)
    #

    class Meta:
        verbose_name = "premier"
        verbose_name_plural = "premiers"
    
    def __str__(self):
        return self.question
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

home/models/signups_model.py
from django.db import models
from cloudinary.models import CloudinaryField
from django.urls import reverse
# Create your models here.

class Signup(models.Model):
    
    #tutorials
    img1 = CloudinaryField('img')
    description = models.CharField(max_length=1000)


    class Meta:
        verbose_name = "signup"
        verbose_name_plural = "signups"
    
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)



    
    

home/models/specs_model.py
from django.db import models
from cloudinary.models import CloudinaryField
from django.urls import reverse
# Create your models here.


class Spec(models.Model):

    # specs
    windows = models.CharField(max_length=100)
    ram = models.CharField(max_length=100)
    vram = models.CharField(max_length=100)

    cpu_1 = models.CharField(max_length=100)
    cpu_2 = models.CharField(max_length=100)
    cpu_3 = models.CharField(max_length=100)
    gpu_1 = models.CharField(max_length=100)
    gpu_2 = models.CharField(max_length=100)
    gpu_3 = models.CharField(max_length=100)
    #

    class Meta:
        verbose_name = "spec"
        verbose_name_plural = "specs"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

home/models/tutorials_model.py
from django.db import models
from cloudinary.models import CloudinaryField
from django.urls import reverse
# Create your models here.

class Tutorial(models.Model):
    
    #tutorials
    img1 = CloudinaryField('img')
    description = models.CharField(max_length=1000)
    video = CloudinaryField(resource_type='video')


    class Meta:
        verbose_name = "tutorial"
        verbose_name_plural = "tutorials"
    
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)



    
    

home/views/agents_view.py
from django.shortcuts import render
from home.models.agents_model import Agent
from django.views.generic import ListView
from django.views.generic import DetailView
# Create your views here.

class AgentListView(ListView):
    context_object_name = "agents"

    queryset = Agent.objects.all()
    template_name = 'agent/agent.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["agents"] = Agent.objects.all().order_by('name')
        return context

class AgentDetailView(DetailView):
    model = Agent
    template_name = 'agent/agent_detail.html'
    
    def get_context_data(self, **kwargs):
        kwargs['agent'] = self.get_object
        return super().get_context_data(**kwargs)

home/views/battlepass_view.py
from django.shortcuts import render
from home.models.battlepass_model import Battlepass
from django.views.generic import ListView


class BattlepassListView(ListView):
    context_object_name = "battlepasss"
    paginate_by = 12
    queryset = Battlepass.objects.all()
    template_name = 'battlepass/battlepass.html' 
    #
    #
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["battlepasss"] = Battlepass.objects.all()
        return context

home/views/gameupdate_view.py
from django.shortcuts import render
from home.models.gameupdates_model import Gameupdate
from django.views.generic import ListView
# Create your views here.

class GameupdateListView(ListView):
    context_object_name = "gameupdates"
    queryset = Gameupdate.objects.all()
    template_name = 'gameupdate/gameupdate.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["gameupdates"] = Gameupdate.objects.all() 
        return context
    

home/views/home_view.py
from django.shortcuts import render
from home.models.home_model import Home
from home.models.newss_model import News
from django.views.generic import ListView


# Create your views here.

class HomeListView(ListView):
    context_object_name = "homes"
    paginate_by = 12
    queryset = Home.objects.all()
    template_name = 'home.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["homes"] = Home.objects.all() 
        return context

class NewsListView(ListView):
    context_object_name = "newss"
    paginate_by = 12
    queryset = News.objects.all()
    template_name = 'news/news.html' 
    #
    #
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["newss"] = News.objects.all().order_by('-datetime')
        return context

home/views/map_view.py
from django.shortcuts import render
from home.models.maps_model import Map
from django.views.generic import ListView
from django.views.generic import DetailView
# Create your views here.

class MapListView(ListView):
    context_object_name = "maps"

    queryset = Map.objects.all()
    template_name = 'map/map.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["maps"] = Map.objects.all().order_by('name')
        return context
    
class MapDetailView(DetailView):
    model = Map
    template_name = 'map/map_detail.html'
    
    def get_context_data(self, **kwargs):
        kwargs['map'] = self.get_object
        return super().get_context_data(**kwargs)

home/views/news_view.py
from django.shortcuts import render
from home.models.newss_model import News
from django.views.generic import ListView
# Create your views here.

class NewsListView(ListView):
    context_object_name = "newss"
    paginate_by = 12
    queryset = News.objects.all()
    template_name = 'news/news.html' 
    #
    #
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["newss"] = News.objects.all().order_by('-datetime')
        return context

home/views/premiers_view.py
from django.shortcuts import render
from home.models.premiers_model import Premier
from django.views.generic import ListView
# Create your views here.

class PremierListView(ListView):
    context_object_name = "premiers"
    queryset = Premier.objects.all()
    template_name = 'premier/premier.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["premiers"] = Premier.objects.all() 
        return context

home/views/specs_view.py
from django.shortcuts import render
from home.models.specs_model import Spec
from django.views.generic import ListView
# Create your views here.


class SpecsListView(ListView):
    context_object_name = "specs"
    paginate_by = 12
    queryset = Spec.objects.all()
    template_name = 'specs/specs.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["specs"] = Spec.objects.all()
        return context

home/views/tutorials_view.py
from django.shortcuts import render
from home.models.tutorials_model import Tutorial
from django.views.generic import ListView
# Create your views here.


class TutorialListView(ListView):
    context_object_name = "tutorials"
    queryset = Tutorial.objects.all()
    template_name = 'tutorial/tutorial.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tutorials"] = Tutorial.objects.all()
        return context

home/templates/home.html
{% extends 'home_base.html' %}
{% load static %}
{% block title %}
    VALORANT: Riot's cometitive game
{% endblock title%}
{% block content %}
  <body>  
    <div class="home-body">
      <div class="videoheader">
        <video autoplay muted loop>
            <source src="https://res.cloudinary.com/dtbkn91rt/video/upload/v1711342161/VALORANT-_t%E1%BB%B1a_game_b%E1%BA%AFn_s%C3%BAng_chi%E1%BA%BFn_thu%E1%BA%ADt_c%E1%BA%A1nh_tranh_5_%C4%91%E1%BA%A5u_5_l%E1%BA%A5y_c%C3%A1c_nh%C3%A2n_v%E1%BA%ADt_l%C3%A0m_n%E1%BB%81n_t%E1%BA%A3ng_t%E1%BB%AB_Riot_Games_wmzqqe.mp4"></source>
      </video>
      </div>

      <div class="indexHeader">
          
            <p>A 5v5 character-based tactical shooter</p>
              <h1>VALORANT</h1>
            <div>
              
              <button class="btn">
                <span class="btn__inner">
                  <span class="btn__slide"></span>
                  <span class="btn__content">PLAY NOW</span>
                </span>
              </button>
              
            </div>
          
      </div>
    <br><br><br>
    


  </div>
      <!--anh-->
      
          <div class="newsimg"><a href="{{news.link}}">
            <img src="{{news.img.url}}"> </a>
          </div>
  </div>

    <!--1.intro-->
    
    <div class = "home-content-body">
      <!--intro-->
      <!-- news-->
          <!--0. latest new-->

    {% comment %} <div class="news-body">
      {% for news in newss %}
    <div>
      <a href="{{news.link}}">   
          <div class="newsbody">
              <div class="newsdes">
                    <h2> {{news.name}} </h2>
                      <p> {{news.description}} </p>
                      <hr>
                  <i> {{news.datetime}} </i>
              </div>
              <!--anh-->
              
                  <div class="newsimg"><a href="{{news.link}}">
                    <img src="{{news.img.url}}"> </a>
                  </div>
          </div>  
      </a>
    </div> 
  
      {% endfor %}  
  </div> {% endcomment %}

        {% for home in homes%}
            <div class="home-bp">
              
              <p> EPISODE {{home.episode}} - ACT {{home.act}} - YEAR {{home.year}}</p>
                <h1> {{home.name}} </h1>
                  <a href="{% url 'home:battlepass' %}">
                    <button class="btn">
                      <span class="btn__inner">
                          <span class="btn__slide"></span>
                          <span class="btn__content" style="text-decoration: none";>Battlepass</span>
                      </span>
                    </button>
                  </a>
              <img src = {{home.img.url}}>
              
            
            </div>
        {% endfor %}
            <div class="home-cb1">
                <div class="home-cb1-text">
                    <h1> we are valorant </h1>
                    <h3> // defy your limits </h3>
                    <p> Blend your style and experience on a global, competitive stage. You have 13 rounds to attack and defend your side using sharp gunplay and tactical abilities. And, with one life per-round, you'll need to think faster than your opponent if you want to survive. Take on foes across Competitive and Unranked modes as well as Deathmatch and Spike Rush.  </p>
                    <a href="{% url 'home:tutorials' %}">
                      <button class="btn">
                        <span class="btn__inner">
                            <span class="btn__slide"></span>
                            <span class="btn__content" style="text-decoration: none";>TUTORIALS</span>
                        </span>
                      </button>
                    </a>
                </div>
                
              
              <!--anh-->
                <div class="home-cb1-img">
                  <video width="700" height="500" autoplay muted loop>
                    <source src="https://res.cloudinary.com/dtbkn91rt/video/upload/v1711342373/VALORANT-_t%E1%BB%B1a_game_b%E1%BA%AFn_s%C3%BAng_chi%E1%BA%BFn_thu%E1%BA%ADt_c%E1%BA%A1nh_tranh_5_%C4%91%E1%BA%A5u_5_l%E1%BA%A5y_c%C3%A1c_nh%C3%A2n_v%E1%BA%ADt_l%C3%A0m_n%E1%BB%81n_t%E1%BA%A3ng_t%E1%BB%AB_Riot_Games_2_xodqgp.mp4"></source>
              </video>
                </div>
            </div>
      <!--agents-->
      <div class="home-cb2">
        
      <!--anh-->
                <div class="home-cb2-img">
                  <img src="https://res.cloudinary.com/dtbkn91rt/image/upload/v1682176104/jett_ieixcr.png"/>
                </div>

                <div class="home-cb2-text">
                  <h1> your agents </h1>
                  <h3> // CREATIVITY IS YOUR GREATEST WEAPON.</h3>
                  <p> Blend your style and experience on a global, competitive stage. You have 13 rounds to attack and defend your side using sharp gunplay and tactical abilities. And, with one life per-round, you'll need to think faster than your opponent if you want to survive. Take on foes across Competitive and Unranked modes as well as Deathmatch and Spike Rush.  </p>
                  <a href="{% url 'home:agents' %}">
                    <button class="btn">
                      <span class="btn__inner">
                          <span class="btn__slide"></span>
                          <span class="btn__content" style="text-decoration: none";>View All Agents</span>
                      </span>
                    </button>
                  </a>
                </div>
    
      </div>



      <!--maps-->
      <div class="home-cb3">
              <div class="home-cb3-text">
                  <h1> your map </h1>
                  <h3>// fight around the world. </h3>
                  <p> Blend your style and experience on a global, competitive stage. You have 13 rounds to attack and defend your side using sharp gunplay and tactical abilities. And, with one life per-round, you'll need to think faster than your opponent if you want to survive. Take on foes across Competitive and Unranked modes as well as Deathmatch and Spike Rush.  </p>
                  <a href="{% url 'home:maps' %}">
                    <button class="btn">
                      <span class="btn__inner">
                          <span class="btn__slide"></span>
                          <span class="btn__content" style="text-decoration: none";>View All MAPS</span>
                      </span>
                    </button>
                  </a>
                </div>
            
            <!--anh-->
              <div class="home-cb3-img">
                <img src="https://res.cloudinary.com/dtbkn91rt/image/upload/v1682176103/mapsIntro_tisdlo.png"/>
              </div>
      </div>
    </div>
    <!--enderintros-->
    
{% endblock %}

home/templates/home_base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %}  {% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/normalize.css'%}" />
    <link rel="stylesheet" href="{% static 'css/style1.css'%}" />
    <link rel="stylesheet" href="{% static 'css/button.css'%}" />
    <link rel="stylesheet" href="{% static 'css/weapon.css'%}" />
    <link rel="stylesheet" href="{% static 'css/agent.css'%}" />
    <link rel="stylesheet" href="{% static 'css/map.css'%}" />
    <link rel="stylesheet" href="{% static 'css/agent_detail.css'%}" />
    <link rel="shortcut icon" type="image/png" href="https://res.cloudinary.com/dtbkn91rt/image/upload/v1680739254/faviconicon_ycc0ow.png">
  </head>
  <header>
    <div class="wrapper">
      <header>
          <nav>
            <ul>
              <li>
                <a href="{% url 'home:home' %}"> <img src="{% static 'img/header-logo.png' %}" alt="Intro Image"  height="30" width="30">  </a>
                <a href="{% url 'home:agents' %}">agents</a>
                <a href="{% url 'home:maps' %}">maps</a>
                <a href="{% url 'home:weapons' %}">arsenals</a>
                <a href="{% url 'home:specs' %}">specs</a>
                <a href="{% url 'home:news' %}">news</a>
                <a href="{% url 'home:battlepass' %}">battlepass</a>
                <a href="{% url 'home:premiers' %}">premiers</a>
                <a href="{% url 'home:tutorials' %}">tutorial</a>
                <a href="https://valorantesports.com/schedule">esport</a>
                <a href="#bottom"> our social </a>
                
                </li>
            </ul>
          </nav>
      </header>
    </div>
    <div class="upper">
      <a href="#top"><img src="{% static 'img/up.png' %}"alt="Intro Image"  height="30" width="30"/></a>
    </div>
  </header>
<body> 
  
{% block content %} 

    <!--body-->
{% endblock content %}
         <script src="{% static 'js/map.js'%}"></script> 
         <footer id="bottom">
          <div class="ender">
              <p>
                <h5> follow us on our social </h5>
                  <a href="https://twitter.com/VALORANT" target="_blank"><img class="socialLink" src="{%static 'img/twitter.png'%}" alt="Twitter" ></img></a>
                  <a href="https://www.facebook.com/VALORANTvn/" target="_blank"><img class="socialLink" src="{% static 'img/facebook.png'%}" alt="Facebook" ></img></a>
                  <a href="https://www.youtube.com/c/VALORANTvn" target="_blank"><img class="socialLink2" src="{% static 'img/youtube.png'%}" alt="YouTube" ></img></a>
                  <a href="https://discord.gg/qqqBa2rfAg" target="_blank"><img class="socialLink2" src="{% static 'img/discord.png'%}" alt="YouTube" ></img></a>
                  <a href="https://www.instagram.com/valorant/?hl=en" target="_blank"><img class="socialLink2" src="{% static 'img/instagram.png'%}" alt="YouTube" ></img></a>
                  <br>
                  
              </p>
          </div>
          <div  class="enderlink">
                  <a href="https://www.riotgames.com/en" target="_blank"><img class="socialLink2" src="https://res.cloudinary.com/dtbkn91rt/image/upload/v1682164854/riot_qr3i31.png" alt="YouTube" ></img></a>
                  <a href="{% url 'home:home' %}" target="_blank"><img class="socialLink2" src="https://res.cloudinary.com/dtbkn91rt/image/upload/v1682164855/logoonhome_dcn8rv.png" alt="YouTube" ></img></a>
          </div>                
                  <p>
                            &copy; 2023 Riot games, inc, riot games, <span>valorant</span>, and any
                            associated logos are trademarks, service marks, and/or registered
                            trademarks of riot games, inc.
                          </p>
                          <img src="https://res.cloudinary.com/dtbkn91rt/image/upload/v1682164808/2.footer_nuwrfn.png"/>
                          <br>
                          
                      <br>
                      <br><div class="updraft">
                            <a href="#top">
                              <img src="{% static 'img/up.png' %}"/>
                            </a>
                            <p> PRESS HERE TO GO ON TOP </p>
                          </div>
                          
                      <br>
                      <br>
                      <br>
                      

                  
        </footer>
      </body>
    </html>

<!-- 
  
  github: https://github.com/omelet2409/playvlr  

  
-->